# Site settings
course_name: Machine Learning for Mathematical Optimization
course_description: "This course introduces automated machine learning approaches for improving optimization algorithms in the presence of a historical dataset or a generator of problem instances from a domain of interest. Topics include automated algorithm configuration, modeling iterative heuristics in the reinforcement learning framework, deep neural networks for modeling combinatorial optimization problems, guiding exact solvers with learned search strategies, learning-theoretic guarantees, and benchmarking/computational considerations. The focus will be on discrete optimization in the integer programming framework, both exact and heuristic."
course_semester: "Fall 2021"

baseurl: "/2021" # the subpath of your site, e.g. /blog/
url: "http://utoronto-ml4opt.github.io/" # the base hostname & protocol for your site

schoolname: "University of Toronto"
schoolurl: "https://utoronto.ca"
twitter_username: UofT 

address: |
    University of Toronto
    Toronto, Ontario
    Canada

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: G-P9097C31HM

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: false
    announcements:
        output: true


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
